### ISSUE TITLE
-DMNN_IMGCODECS=ON: command not found 

### ISSUE THREAD

**Issue by xingyuezhiyun** [wangzhaode/mnn-yolo#1]
-DMNN_IMGCODECS=ON: command not found

**Comment by wangzhaode** [comment]
你是不是没有安装cmake ?

**Comment by xingyuezhiyun** [comment]
> 

安装了啊,添加-DMNN_BUILD_OPENCV选项是可以的,添加-DMNN_IMGCODECS=ON选项就报错,在MNN的CMakeLists.txt也没有找到-DMNN_IMGCODECS=ON这个选项
