### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by sangsasi** [wangzhaode/mnn-yolo#10]
你好，我使用ultralytics-main转换得到的onnx模型，再使用MNNConvert转换得到mnn模型，在c++上跑一直报错，但是下载你的模型能正常运行。
请问你的mnn模型，是怎么转换得到的。

**Comment by wangzhaode** [comment]
就是使用MNNConvert转换的，你转换的模型报错信息是什么能发一下吗

**Comment by sangsasi** [comment]
Broad cast error, dim1 = 4, dim2 = 2
Compute Shape Error for /model.22/Sub_output_0
Can't run session because not resized

**Comment by wangzhaode** [comment]
看起来形状计算不对，能把onnx模型上传一下吗

**Comment by sangsasi** [comment]
yolov8n.pt的下载代码
wget https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt

转onnx的代码
from ultralytics import YOLO
# 加载模型
model = YOLO('yolov8n.pt')  # 加载官方模型
# 导出模型
model.export(format='onnx')

转mnn的代码
MNNConvert -f ONNX --modelFile $onnx_file --MNNModel $mnn_file --bizCode MNN

onnx和mnn的模型文件
[yolov8n_onnx_and_mnn.zip](https://github.com/wangzhaode/mnn-yolo/files/14441811/yolov8n_onnx_and_mnn.zip)

**Comment by sangsasi** [comment]
换成2.4.1版本MNNConvert转换得到的MNN模型可以跑通了。谢谢帮助。

**Comment by wangzhaode** [comment]
> 换成2.4.1版本MNNConvert转换得到的MNN模型可以跑通了。谢谢帮助。

好的 上午开会，还没来得及分析你的模型；能跑通就好
