### ISSUE TITLE
为什么跑python的yolov5demo，使用提供的yolov5n.mnn，跑出来的框在左上角

### ISSUE THREAD

**Issue by BaoZR** [wangzhaode/mnn-yolo#14]
![image](https://github.com/user-attachments/assets/5eb44091-80db-4c91-8770-31ff2d2d7b02)
还有那个跑出来的图片
![image](https://github.com/user-attachments/assets/ad88ff86-2c88-45bc-94ad-a5e8b6f83a35)
框在图片的左上角

**Comment by wangzhaode** [comment]
fixed in https://github.com/wangzhaode/mnn-yolo/commit/f33be79aafb52703ff2493e857cf4de1fb2dcb00

**Comment by BaoZR** [comment]
thank you 
i can see the box and picture
![image](https://github.com/user-attachments/assets/7ddc9a56-f979-426a-9606-8b99062dd740)
