### ISSUE TITLE
main.cpp:36: undefined reference to `MNN::CV::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)' 

### ISSUE THREAD

**Issue by xingyuezhiyun** [wangzhaode/mnn-yolo#2]
main.cpp:36: undefined reference to `MNN::CV::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'

**Comment by wangzhaode** [comment]
是按照readme的流程做的吗？

**Comment by xingyuezhiyun** [comment]
> 是按照readme的流程做的吗？

是的,用的CLion开发工具,你那里能跑起来吗?

**Comment by wangzhaode** [comment]
可以的啊 你是什么系统，把完整的log发一下

**Comment by xingyuezhiyun** [comment]
> 可以的啊 你是什么系统，把完整的log发一下

我用的是Linux ubuntu 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
log就是main.cpp:36: undefined reference to `MNN::CV::imread(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, int) 这一条

**Comment by wangzhaode** [comment]
编译的完整Log；你这个看起来是MNN编译时没有打开README里的宏导致的

**Comment by xingyuezhiyun** [comment]
> 编译的完整Log；你这个看起来是MNN编译时没有打开README里的宏导致的
/home/xingyue/Downloads/CLion-2023.1.2/clion-2023.1.2/bin/cmake/linux/x64/bin/cmake --build /home/xingyue/CLionProjects/MNNTest/cmake-build-debug --target MNNTest -j 3
[1/1] Linking CXX executable MNNTest
FAILED: MNNTest 
: && /usr/bin/c++ -g  CMakeFiles/MNNTest.dir/main.cpp.o -o MNNTest -L/home/xingyue/CLionProjects/MNNTest/libs -Wl,-rpath,/home/xingyue/CLionProjects/MNNTest/libs  -lMNN  -lMNN_Express  -lMNNOpenCV && :
/usr/bin/ld: CMakeFiles/MNNTest.dir/main.cpp.o: in function `detectImage(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/xingyue/CLionProjects/MNNTest/main.cpp:36: undefined reference to `MNN::CV::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
我编译的命令:
mkdir build && cd build && cmake .. -DMNN_BUILD_OPENCV=ON && make -j8
如果加这个选项-DMNN_IMGCODECS=ON 会报找不到,在MNN目录下的CMakeLists.txt里面确实没有找到这个选项

**Comment by xingyuezhiyun** [comment]
![666666](https://github.com/wangzhaode/yolov8-mnn/assets/19636480/4f7293e1-10ae-466a-9ef8-11528a1d6008)
这是工程结构

**Comment by xingyuezhiyun** [comment]
可以把完整demo发我吗? ywb10.8@qq.com
