### ISSUE TITLE
推理结果异常

### ISSUE THREAD

**Issue by MirrorYuChen** [wangzhaode/mnn-yolo#7]
MNN版本：2.5.0
编译器：clion + mingw 8.1
平台：windows 10
运行结果截图：
![image](https://github.com/wangzhaode/yolov8-mnn/assets/49817428/2eee2642-e92c-40c5-ae91-8b7bae9523f8)

**Comment by MirrorYuChen** [comment]
运行指令：../data/yolov8n.mnn ../data/bus.jpg

**Comment by lhz123** [comment]
我们遇到了一样的问题，请问你解决了吗

**Comment by wangzhaode** [comment]
C++之前类型有点错误，已经在：https://github.com/wangzhaode/mnn-yolov8/commit/73f06c0b265c38b3e018542f28944c7d2c2cf0ac 修复了；请更新一下代码再测试一下
