### ISSUE TITLE
80和81行数据类型读取方式反了

### ISSUE THREAD

**Issue by lrjbdss** [wangzhaode/mnn-yolo#8]
https://github.com/wangzhaode/mnn-yolov8/blob/02d8b64482d382a35e9ff581baac8df0664a4c28/cpp/yolov8_demo.cpp#L80C33-L80C33

**Comment by wangzhaode** [comment]
是的，感谢提醒

**Comment by wangzhaode** [comment]
已修复： https://github.com/wangzhaode/mnn-yolov8/commit/73f06c0b265c38b3e018542f28944c7d2c2cf0ac
